

services:
  bankapp-database:
    image: mysql:8.0
    ports:
      - "2002:3306" 
    container_name: bankapp-database
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bankappRoot7@1k2020
      MYSQL_DATABASE: bankapp_db
      MYSQL_USER: bankapp
      MYSQL_PASSWORD: bankapp123
    command: ['mysqld',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]

volumes:
  dbdata:
